# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "iOS beta distribution to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "AZDMV.xcodeproj")

    sync_code_signing(type: "appstore")    # see code signing guide for more information
    build_app(scheme: "AZDMV")
    upload_to_testflight(skip_waiting_for_build_processing: true)

    commit_version_bump(xcodeproj: "AZDMV.xcodeproj")
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "AZDMV.xcworkspace", scheme: "AZDMV-UITests")
    upload_to_app_store(force: true, skip_binary_upload: true, skip_metadata: true)
  end
end
