name: beta

on:
  push:
    branches: [ main ]

jobs:
  beta:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Install CocoaPods Dependencies
      run: pod install
    - name: Setup fastlane
      shell: bash
      env:
        fastlanePK: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
      run: |
        echo "$fastlanePK" > ~/.ssh/id_fastlane
        chmod 600 ~/.ssh/id_fastlane
    - name: Deploy to TestFlight
      run: bundle exec fastlane beta
      env:
        MATCH_GIT_PRIVATE_KEY: ~/.ssh/id_fastlane
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
    - name: Push Version Bump
      run: git push
